"""compliance: policy rules, violations, anomaly findings

Revision ID: 005
Revises: 004
Create Date: 2026-08-17 10:02:48.714341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_tables(bind):
    return set(sa.inspect(bind).get_table_names())


def upgrade() -> None:
    """Upgrade schema.

    Guarded because DB_AUTO_CREATE defaults to true in development: importing the
    app runs `Base.metadata.create_all`, so these tables may already exist by the
    time anyone runs `alembic upgrade head`. Without the guard that ordering
    fails with "relation already exists" and looks like a broken migration.
    """
    present = _existing_tables(op.get_bind())
    if {"policy_rules", "policy_violations", "anomaly_findings"} <= present:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), server_default='internal', nullable=False),
    sa.Column('statute_ref', sa.String(length=120), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_paise', sa.BigInteger(), nullable=True),
    sa.Column('threshold_count', sa.Integer(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('narration_filter', sa.String(length=300), nullable=True),
    sa.Column('direction_scope', sa.String(length=10), server_default='any', nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_policy_rule_user_code')
    )
    op.create_index(op.f('ix_policy_rules_id'), 'policy_rules', ['id'], unique=False)
    op.create_index('ix_policy_rules_user_active', 'policy_rules', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_policy_rules_user_id'), 'policy_rules', ['user_id'], unique=False)
    op.create_table('anomaly_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_anomaly_fingerprint')
    )
    op.create_index(op.f('ix_anomaly_findings_anomaly_type'), 'anomaly_findings', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_id'), 'anomaly_findings', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_occurred_on'), 'anomaly_findings', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_statement_id'), 'anomaly_findings', ['statement_id'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_status'), 'anomaly_findings', ['status'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_transaction_id'), 'anomaly_findings', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_anomaly_findings_user_id'), 'anomaly_findings', ['user_id'], unique=False)
    op.create_index('ix_anomaly_user_status_type', 'anomaly_findings', ['user_id', 'status', 'anomaly_type'], unique=False)
    op.create_table('policy_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_policy_violation_fingerprint')
    )
    op.create_index(op.f('ix_policy_violations_id'), 'policy_violations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_violations_occurred_on'), 'policy_violations', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_policy_violations_rule_id'), 'policy_violations', ['rule_id'], unique=False)
    op.create_index(op.f('ix_policy_violations_status'), 'policy_violations', ['status'], unique=False)
    op.create_index(op.f('ix_policy_violations_transaction_id'), 'policy_violations', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_policy_violations_user_id'), 'policy_violations', ['user_id'], unique=False)
    op.create_index('ix_policy_violations_user_status', 'policy_violations', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    present = _existing_tables(op.get_bind())
    if not ({"policy_rules", "policy_violations", "anomaly_findings"} & present):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_violations_user_status', table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_user_id'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_transaction_id'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_status'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_rule_id'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_occurred_on'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_id'), table_name='policy_violations')
    op.drop_table('policy_violations')
    op.drop_index('ix_anomaly_user_status_type', table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_user_id'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_transaction_id'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_status'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_statement_id'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_occurred_on'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_id'), table_name='anomaly_findings')
    op.drop_index(op.f('ix_anomaly_findings_anomaly_type'), table_name='anomaly_findings')
    op.drop_table('anomaly_findings')
    op.drop_index(op.f('ix_policy_rules_user_id'), table_name='policy_rules')
    op.drop_index('ix_policy_rules_user_active', table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
