#!/usr/bin/env bash
# Runs once, after the dev container is created (postCreateCommand).
#
# Python dependencies are NOT installed here — they are baked into the image by
# .devcontainer/Dockerfile so Codespaces prebuilds can cache them. What is left
# is everything that needs a running database or a freshly generated secret.
#
# Safe to re-run by hand: every step below is conditional.
set -euo pipefail

cd /workspace

log() { printf '\n\033[1;36m[post-create]\033[0m %s\n' "$*"; }

# --- 1. Runtime directories --------------------------------------------------
# main.py creates these on import, but the uploads tree is also written by the
# email and RPA paths, and a missing directory there surfaces as a failed upload
# rather than a failed startup.
mkdir -p uploads/email uploads/rpa_screens logs

# --- 2. .env ------------------------------------------------------------------
# The application reads .env through python-dotenv (app/config.py). Values
# already present in the process environment WIN over the file — so DATABASE_URL
# and REDIS_URL are set by .devcontainer/docker-compose.yml and repeated here
# only so the file is a complete, accurate picture of the local configuration.
#
# Never committed: .env is in .gitignore, and this generates a unique secret per
# codespace rather than shipping one.
if [ -f .env ]; then
    log ".env already exists — left untouched."
else
    log "Generating .env with a per-codespace JWT secret."

    JWT_SECRET="$(python -c 'import secrets; print(secrets.token_urlsafe(64))')"

    # In a codespace, port 8000 is reachable at
    # https://<codespace-name>-8000.<forwarding-domain>. CORS and both OAuth
    # redirect URIs need that exact origin — localhost is not what the browser
    # sends. Outside Codespaces (plain Dev Containers) these variables are
    # unset and localhost is correct, so fall back to it.
    if [ -n "${CODESPACE_NAME:-}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]; then
        PUBLIC_URL="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    else
        PUBLIC_URL="http://localhost:8000"
    fi
    log "Public URL for this container: ${PUBLIC_URL}"

    cat > .env <<ENV
# Generated by .devcontainer/post-create.sh — local development only.
# Delete this file and rebuild the container to regenerate it.
ENVIRONMENT=development

# Supplied by the compose stack as well; kept here so the file is self-contained.
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/backend_db
REDIS_URL=redis://redis:6379/0

# Unique to this container. Rotating it invalidates every issued token.
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

UPLOAD_DIR=uploads
ML_MODELS_DIR=mlmodel/models
CONFIDENCE_THRESHOLD=0.80

LOG_LEVEL=INFO
LOG_DIR=logs
LOG_FILE=app.log

# The forwarded port is served over https by Codespaces, so the browser origin
# is the URL below and not localhost. Add a frontend origin here if you run one.
ALLOWED_ORIGINS=${PUBLIC_URL},http://localhost:8000,http://127.0.0.1:8000,http://localhost:3000

# /docs, /redoc, /openapi.json. On here because this is a development container.
ENABLE_API_DOCS=true

# X-Forwarded-For is only trustworthy behind a proxy that sets it. The
# Codespaces port-forwarder does, but the rate limiter keying off a header any
# client can send is worse than every request sharing one bucket locally, so
# this stays off unless you are specifically testing that path.
TRUST_PROXY_HEADERS=false

# Outbound FX polling, off by default in a dev container (see docker-compose.yml).
FX_REFRESH_ENABLED=false

# --- OAuth mailbox connectors (optional) -------------------------------------
# Both providers require the redirect URI to match byte for byte, and for a
# codespace that means the forwarded https URL below — not localhost. Fill in
# the client id/secret and register these two URIs with the provider.
# MICROSOFT_CLIENT_ID=
# MICROSOFT_CLIENT_SECRET=
# MICROSOFT_TENANT=common
MICROSOFT_REDIRECT_URI=${PUBLIC_URL}/email/oauth/microsoft/callback
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=${PUBLIC_URL}/email/oauth/callback
ENV
fi

# --- 3. Wait for PostgreSQL ---------------------------------------------------
# depends_on/service_healthy already gates container start, but a rebuilt or
# restarted stack can still have the socket refusing connections for a moment,
# and the schema step below must not race it.
log "Waiting for PostgreSQL..."
for _ in $(seq 1 60); do
    if pg_isready -h postgres -p 5432 -U postgres -d backend_db >/dev/null 2>&1; then
        break
    fi
    sleep 2
done

if ! pg_isready -h postgres -p 5432 -U postgres -d backend_db >/dev/null 2>&1; then
    log "PostgreSQL did not become ready. Check: docker compose logs postgres"
    exit 1
fi

# --- 4. Schema ----------------------------------------------------------------
# The migration chain does not build a database from nothing: revision 001
# ALTERs `statements`, so `alembic upgrade head` against an empty database
# fails. A new database is therefore bootstrapped by importing the app
# (DB_AUTO_CREATE is on outside production, so Base.metadata.create_all builds
# every table) and then STAMPED as current. An existing database just upgrades.
# This mirrors the runbook in README.md / docs/POSTGRES_MIGRATION.md.
export PGPASSWORD=postgres
ALEMBIC_TABLE="$(psql -h postgres -U postgres -d backend_db -tAc \
    "SELECT to_regclass('public.alembic_version')" 2>/dev/null || true)"

if [ -z "${ALEMBIC_TABLE//[[:space:]]/}" ]; then
    log "Empty database — creating the schema and stamping it as current."
    python -c "import main"
    python -m alembic stamp head
else
    log "Existing database — applying any outstanding migrations."
    python -m alembic upgrade head
fi

log "Ready. Start the API with:

    python main.py

Then open the forwarded port 8000 (Ports panel) and check /health.
API docs are at /docs. Tests: python -m pytest tests
"
